name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: make build

    - name: Push Docker image
      run: make push
      env:
        DOCKER_ID_USER: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_NAME: movies_docker

     - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.<your-region>.amazonaws.com

    - name: Build and Push Docker image
      run: |
        docker build -t <your-repo-name>:latest .
        docker tag <your-repo-name>:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repo-name>:latest
        docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repo-name>:latest

    