name: IaC Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: |
        echo "Configuring AWS credentials"
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-2

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ID }}.dkr.ecr.us-east-2.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        docker build -t movie-recs:latest .
        docker tag movie-recs:latest ${{ secrets.AWS_ID }}.dkr.ecr.us-east-2.amazonaws.com/movie-recs:latest
        docker push ${{ secrets.AWS_ID }}.dkr.ecr.us-east-2.amazonaws.com/movie-recs:latest
        
    - name: Configure Databricks Credentials
      env:
        DATABRICKS_HOST: ${{ secrets.DB_SERVER_HOSTNAME }}
        DATABRICKS_TOKEN: ${{ secrets.DB_ACCESS_TOKEN }}
      run: |
        echo "Configuring Databricks credentials"
        export DATABRICKS_HOST=$DATABRICKS_HOST
        export DATABRICKS_TOKEN=$DATABRICKS_TOKEN
      
  